new:
  path: /new
  controller: App\Controller\Auth\NewController::new
  methods: [POST]

login:
  path: /
  controller: App\Controller\Auth\LoginController::login
  methods: [POST]

renewToken:
  path: /renewToken
  controller: App\Controller\Auth\RenewTokenController::renewToken
  methods: [GET]