auth_login:
  path: /login
  controller: App\Controller\Auth\LoginController::showLoginForm
  methods: [GET]
auth_register:
  path: /register
  controller: App\Controller\Auth\RegisterController::showRegisterForm
  methods: [GET]


