#index:
#    path: /
#    controller: App\Controller\DefaultController::index



user_edit:
  path: /{_locale}/user/editar/{id}
  defaults: { _controller: App\Controller\RoutingController:editar }
  requirements:
    id: '\d+'
    _locale: es|fr

user_list:
  path: /{_locale}/user/listar/{page}
  defaults: { _controller: App\Controller\RoutingController:listar, page: 1, title: 'users list', "_locale": "es" }
  requirements:
    page: '\d+'
    _locale: es|fr

download:
  path: /{_locale}/user/lits.{_format}
  defaults: { _controller: App\Controller\RoutingController:listar, page: 1, title: 'users list' }
  requirements:
    _format: 'html|json|csv'
    _locale: es|fr

mobile_homepage:
  path: /
  defaults: { _controller: App\Controller\RoutingController:mobile, page: 1, title: 'users list' }
  host: '{project_name}.m.trainingit.es'
  methods: [PUT,POST]
  schemes: [https]
  requirements:
    project_name: proyecto1|proyecto2|proyecto3
    _format: 'html|json|csv'
    _locale: es|fr


homepage:
  path: /
  controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::redirectAction
  defaults:
    route: user_list
    # make a permanent redirection...
    permanent: true
    # ...and keep the original query string parameters
    keepQueryParams: true

generate_url:
  path: /generate_url
  controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::exampleGenerateRL

