#index:
#    path: /
#    controller: App\Controller\DefaultController::index

api_message:
  resource: "routing/message.yaml"
  prefix: /api

api_login:
  resource: "routing/auth.yaml"
  prefix: /api/login/

api_login_check:
  path: /api/login_check



